### ISSUE TITLE
load re-trained model error

### ISSUE THREAD

**Issue by leviome** [krasserm/wdsr#4]
at the beginning,  'demo.py'  ran successfully with pretrained model.
then, after preparing and converting data, I retrained the model by 

`python train.py --dataset ./DIV2K_BIN --outdir ./output --profile wdsr-a-8 --scale 2`

it ran normally for 300 epochs, and I got many new h5 files. when I loaded one of new h5 files, error occurred:

**TypeError: Expected float32, got {'type': 'ndarray', 'value': [114.44399999999999, 111.4605, 103.02000000000001]} of type 'dict' instead.**
could you offer me some suggestions?

**Comment by krasserm** [comment]
Please provide details how you loaded the h5 file.

**Comment by leviome** [comment]
`python demo.py -i ./demo -o ./output --model ./output/20181204-230641/models/epoch-300-psnr-37.7157.h5 `
'**epoch-300-psnr-37.7157.h5**' is the new h5 file. And, 
`python bench.py -i ./output/20181204-230641/models -o bench.json` had the same error information.

**Comment by leviome** [comment]
![image](https://user-images.githubusercontent.com/24760894/49509415-459b1200-f8c0-11e8-873f-031ee16d54b2.png)

**Comment by krasserm** [comment]
I'm afraid I cannot reproduce your problem i.e. the commands you provided work as expected in my environment. What versions of Keras and Tensorflow do you use?

**Comment by krasserm** [comment]
Probably you ran into https://github.com/keras-team/keras/issues/11281

**Comment by leviome** [comment]
tensorflow==1.9.0
tensorflow-gpu==1.9.0
keras==2.2.0
I upgraded keras version to 2.2.4, the error still existed.
may I know your version of tf and keras

**Comment by krasserm** [comment]
You will need to re-train the model as the h5 files have been written with the older Keras version. For a quick test, can you please train the model again for only 1 epoch and then use the generated h5 file with the demo? This should work now. I'm using Keras 2.2.4 and tested with Tensorflow 1.10 and 1.12.

**Comment by leviome** [comment]
thanks a lot!
I retrained it with keras 2.2.4, and the new model is available for demo.py. 
Your suggestions helped much!

**Comment by krasserm** [comment]
You're welcome, glad it worked!

**Comment by ink1** [comment]
this helped me too. consider adding keras=2.2.4 as a requirement.
and many thanks for sharing. much appreciated!

**Comment by nicaogr** [comment]
Sorry but it doesn't work for me to update keras to 2.2.4.
